### ISSUE TITLE
After 1.0.1 update getting Can't resolve 'react-alert-template-basic'

### ISSUE THREAD

**Issue by harshilm-netedge** [schiehll/react-alert-template-basic#12]

**Comment by JungJaeLee-JJ** [comment]
same issue with me

**Comment by samanth619** [comment]
Same Issue with me! What could be the solution ?

**Comment by JungJaeLee-JJ** [comment]
i figure out this by copy & paste every code in node_modules/react-alert-template-basic...😭
good news is it is little!

**Comment by foosean-mu** [comment]
Facing the same issue as well after updating to 1.0.1

**Comment by schiehll** [comment]
Sorry about that, fixed on v1.0.2
